### ISSUE TITLE
Create MVP Front-end (based on WF)

### ISSUE THREAD

**Issue by DeeMcCart** [vinnieOrdobas/ci_national_ai#19]
EPIC:  <epic>

As a **team member** I want to **see a front-end** to achieve **understand what we are offering a user**
As a **user** I want to **accesss the system** so that **I can understand what it offers and learn the functionality** 

### Assumptions or Pre-Requisites:
* Wireframes created
* Rough idea of what we are trying to create from users perspective (chatbot type app, with text-based/ charts/ map outputs)
* Rough idea of how the back-end might be connected in future

### Acceptance Criteria: (Must be completed before task is moved to 'Done')
- [ ] Must be reasonably aligned with wireframe
- [ ] Must reasonably align with what we know about backend/ how we might link

### Tasks

- [ ] Task1
- [ ] Task2
- [ ] Task3
- [ ] Task4

Before changing task status to 'Review' or 'Done' please provide comment (and screenprints if appropriate) as documentary evidence of task completion

**Comment by ray-codeinstitute** [comment]
Have created front end with stubbed flask server to connect to the model api, when it's done.
